# This file was generated by GoReleaser. DO NOT EDIT.
cask "qory" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "484b86945f440a8aff11881f7a5e21d8b671f5e3b23df286125af60064d1c60f"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7d06ce99ef849430cc6f0d3a3c25160a63e4f5eaff42b05bca2cd1c944ae142e"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "822212352804cfeddc30be0372140fc7d6ffc364a640218a8185667e05e5fd8f"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "33afba3f59d823e9eaa635aacf0661c21aee0d085d48ce6046d4b141b851211f"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qory"
  desc "Compose the harness a runtime loads from modules"
  homepage "https://github.com/qoryai/qory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qory"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qory"]
    end
  end

  # No zap stanza required
end
