# This file was generated by GoReleaser. DO NOT EDIT.
cask "qory" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "9a786d2b4319b7cb4e199c6d88f200cf5cdc6bd292e9f7d2d6d57fae8faf60a8"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2099cbbc8731e5b4237bf2db58aa96fdf1c2f2a744712a945a38f610765ea3eb"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ecff5248305aaf4fb5f4d7b4d8da9a537696d116bd6c14b0be9cb4badadab818"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "40ad5c4eb7f2a33bb862bec631c58b07e5c527936d184b9716433aa147c9d548"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qory"
  desc "Compose the harness a runtime loads from modules"
  homepage "https://github.com/qoryai/qory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qory"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qory"]
    end
  end

  # No zap stanza required
end
