# This file was generated by GoReleaser. DO NOT EDIT.
cask "qory" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "57d21099d4cf75192c4d2063a6800dca7f016778464dce113eff0d81ff760656"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "275b6989cbba675d51e607c31514b0844a0c1f28f73ffc2415d6e4b6bba1046b"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb9c0a49885bfc26565ca692e6122f0adca070f63a000a24f37dc8b8ee0268d1"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "089be421c7b17bf177e9af720d36b1f072b1b6b1211bfb619da528d851bdde0c"
      url "https://github.com/qoryai/qory/releases/download/v#{version}/qory_#{version}_linux_amd64.tar.gz"
    end
  end

  name "qory"
  desc "Compose the harness a runtime loads from modules"
  homepage "https://github.com/qoryai/qory"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qory"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qory"]
    end
  end

  # No zap stanza required
end
